CREATE TABLE IF NOT EXISTS academic_programs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_academic_program_name (name),
  CONSTRAINT fk_academic_programs_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_academic_programs_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE users ADD COLUMN IF NOT EXISTS program_id BIGINT UNSIGNED NULL AFTER contact;
ALTER TABLE users ADD INDEX IF NOT EXISTS idx_users_program (program_id);
ALTER TABLE users ADD CONSTRAINT fk_users_program FOREIGN KEY (program_id) REFERENCES academic_programs(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS academic_terms (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  starts_on DATE NOT NULL,
  ends_on DATE NOT NULL,
  is_current TINYINT(1) NOT NULL DEFAULT 0,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE users ADD COLUMN IF NOT EXISTS academic_term_id BIGINT UNSIGNED NULL AFTER program_id;
ALTER TABLE users ADD INDEX IF NOT EXISTS idx_users_academic_term (academic_term_id);
ALTER TABLE users ADD CONSTRAINT fk_users_academic_term FOREIGN KEY (academic_term_id) REFERENCES academic_terms(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS academic_terms (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  starts_on DATE NOT NULL,
  ends_on DATE NOT NULL,
  is_current TINYINT(1) NOT NULL DEFAULT 0,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE users ADD COLUMN IF NOT EXISTS academic_term_id BIGINT UNSIGNED NULL AFTER program_id;
ALTER TABLE users ADD INDEX IF NOT EXISTS idx_users_academic_term (academic_term_id);
ALTER TABLE users ADD CONSTRAINT fk_users_academic_term FOREIGN KEY (academic_term_id) REFERENCES academic_terms(id) ON DELETE SET NULL;
