import { useCallback, useEffect, useMemo, useState } from "react";
import { Download, ExternalLink, RefreshCcw, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { AdminPanel } from "@/features/admin";
import { getApiErrorMessage } from "@/utils/apiError";
import { downloadQueryCsv, fetchQuery, fetchQueryMeta, type QueryDataset, type QueryFilters, type QueryMeta, type QueryResult } from "./api";

const initialFilters = (dataset: QueryDataset): QueryFilters => ({ dataset, search: "", dateFrom: "", dateTo: "" });
const display = (value: unknown) => value === null || value === undefined || value === "" ? "—" : String(value);

const FilterSelect = ({ id, label, value, onChange, options }: { id: string; label: string; value: string; onChange: (value: string) => void; options: { value: string; label: string }[] }) => <div className="space-y-2"><Label htmlFor={id} className="text-xs font-semibold uppercase tracking-[0.16em] text-muted-foreground">{label}</Label><Select value={value || "all"} onValueChange={onChange}><SelectTrigger id={id} className="rounded-none"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All {label.toLowerCase()}s</SelectItem>{options.map((option) => <SelectItem key={option.value} value={option.value}>{option.label}</SelectItem>)}</SelectContent></Select></div>;

const QueryExplorer = () => {
  const [meta, setMeta] = useState<QueryMeta | null>(null); const [filters, setFilters] = useState<QueryFilters>(initialFilters("catalog"));
  const [result, setResult] = useState<QueryResult | null>(null); const [loading, setLoading] = useState(true); const [exporting, setExporting] = useState(false); const [error, setError] = useState("");
  const activeDataset = meta?.datasets.find((dataset) => dataset.value === filters.dataset);
  const setFilter = (key: string, value: string) => setFilters((current) => ({ ...current, [key]: value }));
  const load = useCallback(async (page = 1) => { setLoading(true); setError(""); try { setResult(await fetchQuery({ ...filters, page, limit: 25 })); } catch (failure) { setError(getApiErrorMessage(failure, "Unable to load records. Check the filters and try again.")); } finally { setLoading(false); } }, [filters]);
  useEffect(() => { void fetchQueryMeta().then(setMeta).catch((failure) => setError(getApiErrorMessage(failure, "Unable to load query filters."))); }, []);
  useEffect(() => { void load(1); }, [load]);
  const changeDataset = (dataset: QueryDataset) => setFilters(initialFilters(dataset));
  const previewUrl = useMemo(() => { const params = new URLSearchParams(); Object.entries(filters).forEach(([key, value]) => { if (value && value !== "all") params.set(key, String(value)); }); return `/admin/query/preview?${params.toString()}`; }, [filters]);
  const exportCsv = async () => { setExporting(true); setError(""); try { await downloadQueryCsv(filters); } catch (failure) { setError(getApiErrorMessage(failure, "Unable to download this CSV. Try again.")); } finally { setExporting(false); } };
  const query = activeDataset?.filters ?? [];
  return <div className="space-y-5">
    {error ? <div role="alert" className="flex items-center justify-between gap-3 border border-destructive/40 bg-destructive/5 px-4 py-3 text-sm text-destructive"><span>{error}</span><Button type="button" variant="ghost" size="sm" onClick={() => setError("")}>Dismiss</Button></div> : null}
    <AdminPanel title="Explore records" description="Choose a record type, refine its filters, then inspect, preview, or export the exact matching data.">
      <div className="space-y-5">
        <div className="grid gap-4 md:grid-cols-[minmax(0,1.5fr)_minmax(0,2fr)]">
          <FilterSelect id="query-dataset" label="Record type" value={filters.dataset} onChange={(value) => changeDataset(value as QueryDataset)} options={(meta?.datasets ?? []).map((dataset) => ({ value: dataset.value, label: dataset.label }))} />
          <div className="space-y-2"><Label htmlFor="query-search" className="text-xs font-semibold uppercase tracking-[0.16em] text-muted-foreground">Search</Label><div className="relative"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input id="query-search" className="rounded-none pl-9" value={String(filters.search ?? "")} onChange={(event) => setFilter("search", event.target.value)} placeholder={`Search ${activeDataset?.label.toLowerCase() ?? "records"}`} /></div></div>
        </div>
        <div className="grid gap-4 border-y border-border/70 py-4 md:grid-cols-2 xl:grid-cols-4">
          <div className="space-y-2"><Label htmlFor="query-start" className="text-xs font-semibold uppercase tracking-[0.16em] text-muted-foreground">Start date</Label><Input id="query-start" type="date" className="rounded-none" value={String(filters.dateFrom ?? "")} onChange={(event) => setFilter("dateFrom", event.target.value)} /></div>
          <div className="space-y-2"><Label htmlFor="query-end" className="text-xs font-semibold uppercase tracking-[0.16em] text-muted-foreground">End date</Label><Input id="query-end" type="date" className="rounded-none" value={String(filters.dateTo ?? "")} onChange={(event) => setFilter("dateTo", event.target.value)} /></div>
          {query.includes("materialType") ? <FilterSelect id="query-material" label="Material type" value={String(filters.materialType ?? "all")} onChange={(value) => setFilter("materialType", value)} options={[{ value: "book", label: "Book" }, { value: "thesis", label: "Thesis" }]} /> : null}
          {query.includes("bookType") ? <FilterSelect id="query-book-type" label="Book type" value={String(filters.bookType ?? "all")} onChange={(value) => setFilter("bookType", value)} options={(meta?.bookTypes ?? []).map((item) => ({ value: String(item.id), label: item.name }))} /> : null}
          {query.includes("category") ? <FilterSelect id="query-category" label="Category" value={String(filters.category ?? "all")} onChange={(value) => setFilter("category", value)} options={(filters.dataset === "subscriptions" ? meta?.subscriptionCategories ?? [] : meta?.categories ?? []).map((item) => ({ value: item.value, label: item.value }))} /> : null}
          {query.includes("availability") ? <FilterSelect id="query-availability" label="Availability" value={String(filters.availability ?? "all")} onChange={(value) => setFilter("availability", value)} options={[{ value: "available", label: "Available" }, { value: "unavailable", label: "Unavailable" }]} /> : null}
          {query.includes("condition") ? <FilterSelect id="query-condition" label="Copy condition" value={String(filters.condition ?? "all")} onChange={(value) => setFilter("condition", value)} options={["good", "damaged", "lost"].map((value) => ({ value, label: value[0].toUpperCase() + value.slice(1) }))} /> : null}
          {query.includes("role") || query.includes("borrowerRole") ? <FilterSelect id="query-role" label="Role" value={String(filters[query.includes("role") ? "role" : "borrowerRole"] ?? "all")} onChange={(value) => setFilter(query.includes("role") ? "role" : "borrowerRole", value)} options={(meta?.roles ?? []).map((value) => ({ value, label: value.replace(/_/g, " ") }))} /> : null}
          {query.includes("accountStatus") ? <FilterSelect id="query-account-status" label="Account status" value={String(filters.accountStatus ?? "all")} onChange={(value) => setFilter("accountStatus", value)} options={[{ value: "1", label: "Active" }, { value: "0", label: "Inactive" }]} /> : null}
          {query.includes("program") ? <FilterSelect id="query-program" label="Program / course" value={String(filters.program ?? "all")} onChange={(value) => setFilter("program", value)} options={(meta?.programs ?? []).map((item) => ({ value: String(item.id), label: item.name }))} /> : null}
          {query.includes("status") ? <FilterSelect id="query-status" label="Status" value={String(filters.status ?? "all")} onChange={(value) => setFilter("status", value)} options={(filters.dataset === "borrowings" ? ["borrowed", "overdue", "returned"] : ["pending", "ready", "fulfilled", "cancelled", "expired"]).map((value) => ({ value, label: value }))} /> : null}
          {query.includes("issuedBy") ? <FilterSelect id="query-issued-by" label="Issued by" value={String(filters.issuedBy ?? "all")} onChange={(value) => setFilter("issuedBy", value)} options={(meta?.issuers ?? []).map((item) => ({ value: String(item.id), label: item.name }))} /> : null}
          {query.includes("purpose") ? <FilterSelect id="query-purpose" label="Purpose" value={String(filters.purpose ?? "all")} onChange={(value) => setFilter("purpose", value)} options={[{ value: "entry_exit", label: "Entry / exit" }, { value: "borrowing", label: "Borrowing" }]} /> : null}
          {query.includes("scanType") ? <FilterSelect id="query-scan-type" label="Scan type" value={String(filters.scanType ?? "all")} onChange={(value) => setFilter("scanType", value)} options={[{ value: "check_in", label: "Check in" }, { value: "check_out", label: "Check out" }]} /> : null}
          {query.includes("audience") ? <FilterSelect id="query-audience" label="Audience" value={String(filters.audience ?? "all")} onChange={(value) => setFilter("audience", value)} options={["all", "user", "role"].map((value) => ({ value, label: value === "all" ? "All users" : value }))} /> : null}
          {query.includes("notificationStatus") ? <FilterSelect id="query-notification-status" label="Notification status" value={String(filters.notificationStatus ?? "all")} onChange={(value) => setFilter("notificationStatus", value)} options={["active", "inactive", "expired"].map((value) => ({ value, label: value }))} /> : null}
          {query.includes("subscriptionStatus") ? <FilterSelect id="query-subscription-status" label="Subscription status" value={String(filters.subscriptionStatus ?? "all")} onChange={(value) => setFilter("subscriptionStatus", value)} options={[{ value: "1", label: "Active" }, { value: "0", label: "Inactive" }]} /> : null}
        </div>
        <div className="flex flex-wrap justify-end gap-2"><Button type="button" variant="ghost" className="rounded-none" onClick={() => setFilters(initialFilters(filters.dataset))}>Reset filters</Button><Button type="button" variant="outline" className="rounded-none" onClick={() => window.open(previewUrl, "_blank", "noopener,noreferrer")} disabled={loading}><ExternalLink className="mr-2 h-4 w-4" />Preview CSV</Button><Button type="button" variant="outline" className="rounded-none" onClick={() => void exportCsv()} disabled={exporting}><Download className="mr-2 h-4 w-4" />{exporting ? "Preparing…" : "Download CSV"}</Button><Button type="button" className="rounded-none" onClick={() => void load(1)} disabled={loading}><RefreshCcw className={`mr-2 h-4 w-4 ${loading ? "animate-spin" : ""}`} />Run query</Button></div>
      </div>
    </AdminPanel>
    <AdminPanel title={`${result?.label ?? activeDataset?.label ?? "Records"} results`} description={loading ? "Loading records…" : `${result?.pagination?.total.toLocaleString() ?? 0} matching record(s).`}>
      {result?.rows.length ? <><div className="overflow-x-auto"><table className="w-full min-w-max text-left text-sm"><thead><tr className="border-b border-border bg-muted/30">{result.columns.map((column) => <th key={column.key} className="whitespace-nowrap px-4 py-3 text-xs font-semibold uppercase tracking-[0.14em] text-muted-foreground">{column.label}</th>)}</tr></thead><tbody>{result.rows.map((row, index) => <tr key={`${index}-${String(row[result.columns[0]?.key])}`} className="border-b border-border/70 last:border-b-0 hover:bg-muted/20">{result.columns.map((column) => <td key={column.key} className="max-w-[26rem] whitespace-nowrap px-4 py-3 text-foreground">{display(row[column.key])}</td>)}</tr>)}</tbody></table></div>{result.pagination && result.pagination.totalPages > 1 ? <div className="mt-4 flex items-center justify-between gap-3 border-t border-border/70 pt-4"><Button variant="outline" className="rounded-none" disabled={loading || result.pagination.page <= 1} onClick={() => void load(result.pagination!.page - 1)}>Previous</Button><p className="text-sm text-muted-foreground">Page {result.pagination.page} of {result.pagination.totalPages}</p><Button variant="outline" className="rounded-none" disabled={loading || result.pagination.page >= result.pagination.totalPages} onClick={() => void load(result.pagination!.page + 1)}>Next</Button></div> : null}</> : <div className="border border-dashed border-border/80 bg-muted/20 px-6 py-10 text-center text-sm text-muted-foreground">{loading ? "Loading query results…" : "No records match these filters."}</div>}
    </AdminPanel>
  </div>;
};

export default QueryExplorer;
