import { useEffect, useMemo, useState } from "react";
import { Download, Loader2, Printer } from "lucide-react";
import { useSearchParams } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { getApiErrorMessage } from "@/utils/apiError";
import { downloadReportCsv, fetchReportPreview, type QueryReport, type ReportFilters, type ReportResult } from "./api";
import { formatQueryGeneratedAt, formatQueryValue } from "./format";
const valid = new Set<QueryReport>(["fined", "daily_users", "date_due", "top_users", "daily_stats", "resource_usage"]);
export default function ReportPreview() { const [params] = useSearchParams(); const filters = useMemo(() => { const raw = Object.fromEntries(params.entries()) as ReportFilters; return { ...raw, report: valid.has(raw.report) ? raw.report : "fined" }; }, [params]); const [result,setResult]=useState<ReportResult|null>(null); const [error,setError]=useState(""); const [loading,setLoading]=useState(true); const [generated,setGenerated]=useState<Date|null>(null); const [downloading,setDownloading]=useState(false); useEffect(()=>{ void fetchReportPreview(filters).then((value)=>{setResult(value);setGenerated(new Date());}).catch((failure)=>setError(getApiErrorMessage(failure,"Unable to prepare this preview."))).finally(()=>setLoading(false)); },[filters]); const download=async()=>{setDownloading(true);try{await downloadReportCsv(filters);}catch(failure){setError(getApiErrorMessage(failure,"Unable to download this report."));}finally{setDownloading(false);}}; return <main className="min-h-screen bg-background px-4 py-6 text-foreground sm:px-8"><div className="mx-auto max-w-[1600px] space-y-5"><header className="flex flex-col gap-4 border-b border-border pb-5 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl font-semibold" style={{fontFamily:"var(--font-heading)"}}>{result?.label ?? "Report"} preview</h1><p className="mt-2 text-sm text-muted-foreground">{generated ? `Generated ${formatQueryGeneratedAt(generated)} · ` : ""}{result?.rows.length ?? 0} rows</p></div><div className="flex gap-2 print:hidden"><Button variant="outline" className="rounded-none" onClick={()=>window.print()}><Printer className="mr-2 h-4 w-4"/>Print</Button><Button className="rounded-none" disabled={!result||downloading} onClick={()=>void download()}>{downloading?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<Download className="mr-2 h-4 w-4"/>}Download CSV</Button></div></header>{error&&<p role="alert" className="border border-destructive/40 bg-destructive/5 px-4 py-3 text-sm text-destructive">{error}</p>}{loading?<div className="flex min-h-64 items-center justify-center text-sm text-muted-foreground"><Loader2 className="mr-2 h-4 w-4 animate-spin"/>Preparing preview…</div>:result&&<section className="overflow-hidden border border-border bg-card"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b border-border bg-muted/30">{result.columns.map((column)=><th key={column.key} className="px-4 py-3 text-xs font-semibold text-muted-foreground">{column.label}</th>)}</tr></thead><tbody className="divide-y divide-border">{result.rows.map((row,index)=><tr key={index}>{result.columns.map((column)=><td key={column.key} className="px-4 py-3">{formatQueryValue(row[column.key],column.type)}</td>)}</tr>)}</tbody></table></div>{!result.rows.length&&<p className="px-5 py-12 text-center text-sm text-muted-foreground">No rows match this report.</p>}</section>}</div></main>; }
