module.exports = {
  authRoutes: require("./auth/auth.routes"),
  adminRoutes: require("./admin/admin.routes"),
  catalogRoutes: require("./catalog/catalog.routes"),
  publicCatalogRoutes: require("./catalog/catalog.public.routes"),
  recommendationPublicRoutes: require("./recommendations/recommendations.public.routes"),
  recommendationRoutes: require("./recommendations/recommendations.routes"),
  borrowingRoutes: require("./borrowing/borrowing.routes"),
  reservationRoutes: require("./reservation/reservation.routes"),
  adminReservationRoutes: require("./reservation/adminReservation.routes"),
  circulationRoutes: require("./circulation/circulation.routes"),
  bulletinRoutes: require("./bulletin/bulletin.routes"),
  eventRoutes: require("./events/events.routes"),
  aboutRoutes: require("./about/about.routes"),
  attendanceRoutes: require("./attendance/attendance.routes"),
  subscriptionsRoutes: require("./subscriptions/subscriptions.routes"),
  analyticsRoutes: require("./analytics/analytics.routes"),
  analyticsAdminRoutes: require("./analytics/analytics.admin.routes"),
  myLibraryRoutes: require("./my-library/my-library.routes"),
  notificationsRoutes: require("./notifications/notifications.routes"),
  librarySettingsRoutes: require("./library-settings/library-settings.routes"),
  backupRoutes: require("./backup/backup.routes"),
  clearanceRoutes: require("./clearance/clearance.routes"),
  siteContentRoutes: require("./site-content/site-content.routes"),
  userGuideRoutes: require("./user-guide/user-guide.routes"),
  queryRoutes: require("./query/query.routes"),
};
