import { useEffect, useState, type FormEvent } from "react";
import { BookOpen, CalendarDays, CalendarOff } from "lucide-react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { AdminPage, AdminPanel } from "./components/AdminPage";
import { ContentRowsSkeleton } from "@/components/ui/content-skeletons";
import { createAcademicProgram, createAcademicTerm, createLibraryHoliday, fetchAcademicPrograms, fetchAcademicTerms, fetchLibrarySettings, setCurrentAcademicTerm, type AcademicProgram, type AcademicTerm, type LibraryHoliday } from "./adminLibrarySettings/api";

const fmt = (v: string) => new Date(v).toLocaleDateString();
export default function AcademicSettings() {
  const [tab, setTab] = useState("terms"), [loading, setLoading] = useState(true), [terms, setTerms] = useState<AcademicTerm[]>([]), [programs, setPrograms] = useState<AcademicProgram[]>([]), [holidays, setHolidays] = useState<LibraryHoliday[]>([]);
  const [term, setTerm] = useState({ name: "", starts_on: "", ends_on: "", is_current: false }), [program, setProgram] = useState(""), [holiday, setHoliday] = useState({ name: "", holiday_date: "", description: "" });
  const load = async () => { setLoading(true); const [s,p,t] = await Promise.all([fetchLibrarySettings(), fetchAcademicPrograms(), fetchAcademicTerms()]); setHolidays(s.holidays); setPrograms(p); setTerms(t); setLoading(false); };
  useEffect(() => { void load(); }, []);
  const form = (onSubmit: (e: FormEvent) => void, children: React.ReactNode) => <form className="space-y-4" onSubmit={onSubmit}>{children}</form>;
  const list = (rows: { id: number; name: string }[], empty: string, extra?: (row: any) => React.ReactNode) => loading ? <div className="p-5"><ContentRowsSkeleton rows={4}/></div> : <div className="divide-y divide-border">{rows.map(row => <div key={row.id} className="flex items-center justify-between gap-3 px-5 py-4"><p className="font-medium">{row.name}</p>{extra?.(row)}</div>)}{!rows.length && <p className="p-5 text-sm text-muted-foreground">{empty}</p>}</div>;
  const Header = ({ icon: Icon, title, detail }: any) => <div className="flex items-start gap-3 border-b border-border py-5"><div className="flex h-9 w-9 items-center justify-center border border-warning/30 bg-warning/10 text-warning"><Icon className="h-4 w-4" /></div><div><h2 className="text-lg font-semibold" style={{fontFamily:"var(--font-heading)"}}>{title}</h2><p className="mt-1 text-sm text-muted-foreground">{detail}</p></div></div>;
  return <AdminPage title="Academic settings" contentWidth="wide"><Tabs value={tab} onValueChange={setTab}><div className="border-y border-border bg-muted/20 px-2 py-2 sm:px-3"><TabsList className="h-auto w-full justify-start gap-1 overflow-x-auto rounded-none bg-transparent p-0"><TabsTrigger value="terms" className="gap-2 rounded-sm px-3 py-2 text-xs"><CalendarDays className="h-4 w-4"/>Terms</TabsTrigger><TabsTrigger value="programs" className="gap-2 rounded-sm px-3 py-2 text-xs"><BookOpen className="h-4 w-4"/>Programs / Courses</TabsTrigger><TabsTrigger value="holidays" className="gap-2 rounded-sm px-3 py-2 text-xs"><CalendarOff className="h-4 w-4"/>Holidays</TabsTrigger></TabsList></div>
  <TabsContent value="terms" className="mt-0"><Header icon={CalendarDays} title="Academic terms" detail="Expired terms require students to revalidate their library card, without preventing sign-in."/><div className="mt-5 grid gap-5 lg:grid-cols-2"><AdminPanel title="Add term">{form(e=>{e.preventDefault(); void createAcademicTerm(term).then(()=>{setTerm({name:"",starts_on:"",ends_on:"",is_current:false});return load();});},<><div><Label>Term name</Label><Input className="mt-2" value={term.name} onChange={e=>setTerm({...term,name:e.target.value})} required/></div><div className="grid gap-3 sm:grid-cols-2"><Input type="date" value={term.starts_on} onChange={e=>setTerm({...term,starts_on:e.target.value})} required/><Input type="date" value={term.ends_on} onChange={e=>setTerm({...term,ends_on:e.target.value})} required/></div><label className="flex gap-2 text-sm"><input type="checkbox" checked={term.is_current} onChange={e=>setTerm({...term,is_current:e.target.checked})}/>Make current term</label><Button>Add term</Button></>)}</AdminPanel><AdminPanel title="Configured terms" contentClassName="p-0">{list(terms,"No academic terms yet.",row=><div className="flex items-center gap-3"><span className="text-sm text-muted-foreground">{fmt(row.starts_on)} – {fmt(row.ends_on)}</span>{row.is_current?<span className="text-sm text-success">Current</span>:<Button size="sm" variant="outline" onClick={()=>void setCurrentAcademicTerm(row.id).then(load)}>Set current</Button>}</div>)}</AdminPanel></div></TabsContent>
  <TabsContent value="programs" className="mt-0"><Header icon={BookOpen} title="Programs / Courses" detail="These are the optional standardized choices available in User Management."/><div className="mt-5 grid gap-5 lg:grid-cols-2"><AdminPanel title="Add program / course">{form(e=>{e.preventDefault();void createAcademicProgram(program).then(()=>{setProgram("");return load();});},<><Input value={program} onChange={e=>setProgram(e.target.value)} placeholder="BS Information Technology" required/><Button>Add program / course</Button></>)}</AdminPanel><AdminPanel title="Configured programs / courses" contentClassName="p-0">{list(programs,"No programs / courses yet.")}</AdminPanel></div></TabsContent>
  <TabsContent value="holidays" className="mt-0"><Header icon={CalendarOff} title="Holidays" detail="Active holidays extend affected circulation due dates."/><div className="mt-5 grid gap-5 lg:grid-cols-2"><AdminPanel title="Add holiday">{form(e=>{e.preventDefault();void createLibraryHoliday(holiday).then(()=>{setHoliday({name:"",holiday_date:"",description:""});return load();});},<><Input value={holiday.name} onChange={e=>setHoliday({...holiday,name:e.target.value})} placeholder="Holiday name" required/><Input type="date" value={holiday.holiday_date} onChange={e=>setHoliday({...holiday,holiday_date:e.target.value})} required/><Button>Add holiday</Button></>)}</AdminPanel><AdminPanel title="Configured holidays" contentClassName="p-0">{list(holidays,"No holidays yet.",row=><span className="text-sm text-muted-foreground">{fmt(row.holiday_date)}</span>)}</AdminPanel></div></TabsContent></Tabs></AdminPage>;
}
